### ISSUE TITLE
Add actual maps instead of placeholders

### ISSUE THREAD

**Issue by ajones55555** [aej11a/meal-sharing-site#26]

**Comment by JDPablo** [comment]
home page map will be semi-static image: user's location pinned in center of map with pins of nearby meals (~1 mile radius in display?) retrieved from database. no zooming/panning functionality but pins and location will update on page refresh (new image) [not sure if actually possible but will see]

**Comment by JDPablo** [comment]
https://leafletjs.com/ (?)

**Comment by JDPablo** [comment]
ignore above.
next step:
pass meals into map.js from home.js (line 32ish)
inside map.js render pins for each of the closest meals
