### ISSUE TITLE
Location: Create Function to Get Coordinates from Address

### ISSUE THREAD

**Issue by ajones55555** [aej11a/meal-sharing-site#9]
We need to accept addresses in text form and use the Google Maps API to get coordinates and save them in our DB with the meal info. After creating the function, we should USE this function in the Meal Creation REST API method.

**Comment by JDPablo** [comment]
Edited: addresses still accepted in text form, but using Positionstack API instead of Google Maps (cost). Function can be called and will return longitude and latitude of given address.
